#!/bin/sh -e

dmenu_VERSION=4.5
lsx_VERSION=0.1
lsw_VERSION=0.2
slock_VERSION=1.1
sselp_VERSION=0.2
swarp_VERSION=0.1
ssid_VERSION=0.1
tabbed_VERSION=0.5
wmname_VERSION=0.1
sprop_VERSION=0.1
xssstate_VERSION=1.1

CURRENT_VERSION=40

TMPDIR=$(mktemp --tmpdir=.. -d suckless-tools.XXXX)
CURDIR=$(pwd)

download_tarball(){
    tool=$1
    version=$2

    echo Downloading $tool-$version...
    wget -q http://dl.suckless.org/tools/$tool-$version.tar.gz -O $CURDIR/suckless-tools_$CURRENT_VERSION.orig-$tool.tar.gz
}

for tool in dmenu lsx lsw slock sselp swarp ssid tabbed wmname sprop xssstate; do
    download_tarball $tool $(eval echo "\$${tool}_VERSION")
done

echo Creating empty suckless-tools_$CURRENT_VERSION.orig.tar.gz
mkdir -p $TMPDIR/suckless-tools_$CURRENT_VERSION
cd $TMPDIR
tar --owner root --group root --mode a+rX -cvf - suckless-tools_$CURRENT_VERSION | gzip -9 > $CURDIR/suckless-tools_$CURRENT_VERSION.orig.tar.gz
rm -rf $TMPDIR

echo Source tarballs are ready

