.TH SLOCK 1 "2015-09-12" "1.2" "suckless-tools"

.SH NAME
slock \- simple screen locker

.SH SYNOPSIS
.B slock
.RB [ \-v ]

.SH DESCRIPTION
.B slock
is a simple screen locker utility for X.
The screen will be kept in an inert state until
the user types his password. In doing so there
is no visual indication that anything is going on,
except possibly a slight glow from the background.

.SH OPTIONS
.B slock
prints its version when fed with \fB\-v\fR.

.SH ENVIRONMENT
.B slock
uses DISPLAY to determine which display to act on.

.SH SEE ALSO
.B Homepage
<\fIhttp://www.suckless.org/\fR>

.SH AUTHOR
slock was written by Anselm R. Garbe <\fIgarbeam@gmail.com\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel@debian.org\fR>,
for the Debian project (but may be used by others).
