.TH SLOCK 1 "2008-08-03" "0.9" "suckless-tools"

.SH NAME
slock \- simple screen locker

.SH SYNOPSIS
.B slock

.SH DESCRIPTION
.B slock
is a simple screen locker utility for X,

.SH OPTIONS
.B slock
has no options.

.SH SEE ALSO
.B Homepage
<\fIhttp://www.suckless.org/\fR>

.SH AUTHOR
slock was written by Anselm R. Garbe <\fIgarbeam@gmail.com\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel@debian.org\fR>, for the Debian project (but may be used by others).
