.TH SSELP 1 "2015-09-12" "0.2" "suckless-tools"

.SH NAME
sselp \- simple X selection printer 

.SH SYNOPSIS
.B sselp
.RI "[\-v]"

.SH DESCRIPTION
.B sselp
prints the X selection to standard out. 
If there is no X client owning the selection it just exits. 
Useful for scripts where you can query the X selection without pressing 
mouse Button2 in cumbersome ways.

.SH OPTIONS
.B sselp
prints its version when fed with \fB\-v\fR.

.SH SEE ALSO
.B Homepage
<\fIhttp://www.suckless.org/\fR>

.SH AUTHOR
sselp was written by Anselm R. Garbe <\fIgarbeam@gmail.com\fR> and Sander van Dijk <\fIa.h.vandijk@gmail.com\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel@debian.org\fR>, for the Debian project (but may be used by others).
