.TH SSID 1 "2008-08-03" "0.1" "suckless-tools"

.SH NAME
ssid \- simple setsid

.SH SYNOPSIS
.B ssid
.RB [ -v ]
.IR cmd " [ " args " ]"

.SH DESCRIPTION
.B ssid
is an extremely simple setsid replacement.
It executes any given command after first
assuming the present session identity,
and possibly after forking to get a correct
process group.

.SH OPTIONS
.B ssid
only prints its version when fed with \fB\-v\fR.

.SH NOTES
Like with all forking software, the shell interpreter
might misplace a line feed when displaying output
from the invoked command. This is a timing artefact.

.SH SEE ALSO
.B Homepage
<\fIhttp://www.suckless.org/\fR>

.SH AUTHOR
ssid was written by Anselm R. Garbe <\fIgarbeam@gmail.com\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel@debian.org\fR>,
for the Debian project (but may be used by others).
