.TH SSID 1 "2008-08-03" "0.1" "suckless-tools"

.SH NAME
ssid \- simple setsid

.SH SYNOPSIS
.B ssid

.SH DESCRIPTION
.B ssid
is an extremly simple setsid replacement.

.SH OPTIONS
.B ssid
has no options.

.SH SEE ALSO
.B Homepage
<\fIhttp://www.suckless.org/\fR>

.SH AUTHOR
ssid was written by Anselm R. Garbe <\fIgarbeam@gmail.com\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel@debian.org\fR>, for the Debian project (but may be used by others).
