.TH SWARP 1 "2008-08-03" "0.1" "suckless-tools"

.SH NAME
swarp \- simple pointer warp

.SH SYNOPSIS
.B swarp
.RB [ \-v "] "
.I xpos ypos

.SH DESCRIPTION
.B swarp
is a generic pointer warping utility for X.
The pointer is moved to the indicated absolute position,
giving focus to the root window.

.SH OPTIONS
.B swarp
prints its version when fed with \fB\-v\fR.

.SH ENVIRONMENT
.B swarp
uses DISPLAY to determine which display to act on.

.SH SEE ALSO
.B Homepage
<\fIhttp://www.suckless.org/\fR>

.SH AUTHOR
swarp was written by Anselm R. Garbe <\fIgarbeam@gmail.com\fR> and
Sander van Dijk <\fIa.h.vandijk@gmail.com\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel@debian.org\fR>,
for the Debian project (but may be used by others).
